/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/_dashboard/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as ApiUploadthingRouteImport } from './routes/api/uploadthing'
import { Route as AuthVerifyRouteImport } from './routes/_auth/verify'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as DashboardContentRouteRouteImport } from './routes/_dashboard/_content/route'
import { Route as DashboardContentWalletIndexRouteImport } from './routes/_dashboard/_content/wallet/index'
import { Route as DashboardContentTicketsIndexRouteImport } from './routes/_dashboard/_content/tickets/index'
import { Route as DashboardContentTeamsIndexRouteImport } from './routes/_dashboard/_content/teams/index'
import { Route as DashboardContentPlayersIndexRouteImport } from './routes/_dashboard/_content/players/index'
import { Route as DashboardContentCompetitionsIndexRouteImport } from './routes/_dashboard/_content/competitions/index'
import { Route as DashboardContentArticlesIndexRouteImport } from './routes/_dashboard/_content/articles/index'
import { Route as DashboardContentAgentsIndexRouteImport } from './routes/_dashboard/_content/agents/index'
import { Route as DashboardContentAdminIndexRouteImport } from './routes/_dashboard/_content/admin/index'
import { Route as DashboardContentAgentsFixturesRouteImport } from './routes/_dashboard/_content/agents/fixtures'
import { Route as DashboardContentCompetitionsCompIdRouteRouteImport } from './routes/_dashboard/_content/competitions/$compId/route'
import { Route as DashboardContentArticlesCreateIndexRouteImport } from './routes/_dashboard/_content/articles/create/index'
import { Route as DashboardContentArticlesArticleIdEditRouteImport } from './routes/_dashboard/_content/articles/$articleId/edit'
import { Route as DashboardContentCompetitionsCompIdStatsRouteRouteImport } from './routes/_dashboard/_content/competitions/$compId/stats/route'
import { Route as DashboardContentCompetitionsCompIdSettingsRouteRouteImport } from './routes/_dashboard/_content/competitions/$compId/_settings/route'
import { Route as DashboardContentCompetitionsCompIdTeamsIndexRouteImport } from './routes/_dashboard/_content/competitions/$compId/teams/index'
import { Route as DashboardContentCompetitionsCompIdStatsIndexRouteImport } from './routes/_dashboard/_content/competitions/$compId/stats/index'
import { Route as DashboardContentCompetitionsCompIdPlayersIndexRouteImport } from './routes/_dashboard/_content/competitions/$compId/players/index'
import { Route as DashboardContentCompetitionsCompIdLeaguesIndexRouteImport } from './routes/_dashboard/_content/competitions/$compId/leagues/index'
import { Route as DashboardContentCompetitionsCompIdFixturesIndexRouteImport } from './routes/_dashboard/_content/competitions/$compId/fixtures/index'
import { Route as DashboardContentCompetitionsCompIdSettingsIndexRouteImport } from './routes/_dashboard/_content/competitions/$compId/_settings/index'
import { Route as DashboardContentCompetitionsCompIdStatsTeamsRouteImport } from './routes/_dashboard/_content/competitions/$compId/stats/teams'
import { Route as DashboardContentCompetitionsCompIdPlayersCreateRouteImport } from './routes/_dashboard/_content/competitions/$compId/players/create'
import { Route as DashboardContentCompetitionsCompIdFixturesReviewRouteImport } from './routes/_dashboard/_content/competitions/$compId/fixtures/review'
import { Route as DashboardContentCompetitionsCompIdSettingsImagesRouteImport } from './routes/_dashboard/_content/competitions/$compId/_settings/images'
import { Route as DashboardContentCompetitionsCompIdSettingsDivisionsRouteImport } from './routes/_dashboard/_content/competitions/$compId/_settings/divisions'
import { Route as DashboardContentCompetitionsCompIdFixturesFixIdRouteRouteImport } from './routes/_dashboard/_content/competitions/$compId/fixtures/$fixId/route'
import { Route as DashboardContentCompetitionsCompIdTeamsTeamIdIndexRouteImport } from './routes/_dashboard/_content/competitions/$compId/teams/$teamId/index'
import { Route as DashboardContentCompetitionsCompIdFixturesFixIdIndexRouteImport } from './routes/_dashboard/_content/competitions/$compId/fixtures/$fixId/index'
import { Route as DashboardContentCompetitionsCompIdPlayersPlayerIdEditRouteImport } from './routes/_dashboard/_content/competitions/$compId/players/$playerId/edit'
import { Route as DashboardContentCompetitionsCompIdFixturesFixIdReviewRouteImport } from './routes/_dashboard/_content/competitions/$compId/fixtures/$fixId/review'
import { Route as DashboardContentCompetitionsCompIdFixturesFixIdRawEventsRouteImport } from './routes/_dashboard/_content/competitions/$compId/fixtures/$fixId/raw-events'
import { Route as DashboardContentCompetitionsCompIdFixturesFixIdPlayerStatsRouteImport } from './routes/_dashboard/_content/competitions/$compId/fixtures/$fixId/player-stats'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadthingRoute = ApiUploadthingRouteImport.update({
  id: '/api/uploadthing',
  path: '/api/uploadthing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const DashboardContentRouteRoute = DashboardContentRouteRouteImport.update({
  id: '/_content',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardContentWalletIndexRoute =
  DashboardContentWalletIndexRouteImport.update({
    id: '/wallet/',
    path: '/wallet/',
    getParentRoute: () => DashboardContentRouteRoute,
  } as any)
const DashboardContentTicketsIndexRoute =
  DashboardContentTicketsIndexRouteImport.update({
    id: '/tickets/',
    path: '/tickets/',
    getParentRoute: () => DashboardContentRouteRoute,
  } as any)
const DashboardContentTeamsIndexRoute =
  DashboardContentTeamsIndexRouteImport.update({
    id: '/teams/',
    path: '/teams/',
    getParentRoute: () => DashboardContentRouteRoute,
  } as any)
const DashboardContentPlayersIndexRoute =
  DashboardContentPlayersIndexRouteImport.update({
    id: '/players/',
    path: '/players/',
    getParentRoute: () => DashboardContentRouteRoute,
  } as any)
const DashboardContentCompetitionsIndexRoute =
  DashboardContentCompetitionsIndexRouteImport.update({
    id: '/competitions/',
    path: '/competitions/',
    getParentRoute: () => DashboardContentRouteRoute,
  } as any)
const DashboardContentArticlesIndexRoute =
  DashboardContentArticlesIndexRouteImport.update({
    id: '/articles/',
    path: '/articles/',
    getParentRoute: () => DashboardContentRouteRoute,
  } as any)
const DashboardContentAgentsIndexRoute =
  DashboardContentAgentsIndexRouteImport.update({
    id: '/agents/',
    path: '/agents/',
    getParentRoute: () => DashboardContentRouteRoute,
  } as any)
const DashboardContentAdminIndexRoute =
  DashboardContentAdminIndexRouteImport.update({
    id: '/admin/',
    path: '/admin/',
    getParentRoute: () => DashboardContentRouteRoute,
  } as any)
const DashboardContentAgentsFixturesRoute =
  DashboardContentAgentsFixturesRouteImport.update({
    id: '/agents/fixtures',
    path: '/agents/fixtures',
    getParentRoute: () => DashboardContentRouteRoute,
  } as any)
const DashboardContentCompetitionsCompIdRouteRoute =
  DashboardContentCompetitionsCompIdRouteRouteImport.update({
    id: '/competitions/$compId',
    path: '/competitions/$compId',
    getParentRoute: () => DashboardContentRouteRoute,
  } as any)
const DashboardContentArticlesCreateIndexRoute =
  DashboardContentArticlesCreateIndexRouteImport.update({
    id: '/articles/create/',
    path: '/articles/create/',
    getParentRoute: () => DashboardContentRouteRoute,
  } as any)
const DashboardContentArticlesArticleIdEditRoute =
  DashboardContentArticlesArticleIdEditRouteImport.update({
    id: '/articles/$articleId/edit',
    path: '/articles/$articleId/edit',
    getParentRoute: () => DashboardContentRouteRoute,
  } as any)
const DashboardContentCompetitionsCompIdStatsRouteRoute =
  DashboardContentCompetitionsCompIdStatsRouteRouteImport.update({
    id: '/stats',
    path: '/stats',
    getParentRoute: () => DashboardContentCompetitionsCompIdRouteRoute,
  } as any)
const DashboardContentCompetitionsCompIdSettingsRouteRoute =
  DashboardContentCompetitionsCompIdSettingsRouteRouteImport.update({
    id: '/_settings',
    getParentRoute: () => DashboardContentCompetitionsCompIdRouteRoute,
  } as any)
const DashboardContentCompetitionsCompIdTeamsIndexRoute =
  DashboardContentCompetitionsCompIdTeamsIndexRouteImport.update({
    id: '/teams/',
    path: '/teams/',
    getParentRoute: () => DashboardContentCompetitionsCompIdRouteRoute,
  } as any)
const DashboardContentCompetitionsCompIdStatsIndexRoute =
  DashboardContentCompetitionsCompIdStatsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardContentCompetitionsCompIdStatsRouteRoute,
  } as any)
const DashboardContentCompetitionsCompIdPlayersIndexRoute =
  DashboardContentCompetitionsCompIdPlayersIndexRouteImport.update({
    id: '/players/',
    path: '/players/',
    getParentRoute: () => DashboardContentCompetitionsCompIdRouteRoute,
  } as any)
const DashboardContentCompetitionsCompIdLeaguesIndexRoute =
  DashboardContentCompetitionsCompIdLeaguesIndexRouteImport.update({
    id: '/leagues/',
    path: '/leagues/',
    getParentRoute: () => DashboardContentCompetitionsCompIdRouteRoute,
  } as any)
const DashboardContentCompetitionsCompIdFixturesIndexRoute =
  DashboardContentCompetitionsCompIdFixturesIndexRouteImport.update({
    id: '/fixtures/',
    path: '/fixtures/',
    getParentRoute: () => DashboardContentCompetitionsCompIdRouteRoute,
  } as any)
const DashboardContentCompetitionsCompIdSettingsIndexRoute =
  DashboardContentCompetitionsCompIdSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardContentCompetitionsCompIdSettingsRouteRoute,
  } as any)
const DashboardContentCompetitionsCompIdStatsTeamsRoute =
  DashboardContentCompetitionsCompIdStatsTeamsRouteImport.update({
    id: '/teams',
    path: '/teams',
    getParentRoute: () => DashboardContentCompetitionsCompIdStatsRouteRoute,
  } as any)
const DashboardContentCompetitionsCompIdPlayersCreateRoute =
  DashboardContentCompetitionsCompIdPlayersCreateRouteImport.update({
    id: '/players/create',
    path: '/players/create',
    getParentRoute: () => DashboardContentCompetitionsCompIdRouteRoute,
  } as any)
const DashboardContentCompetitionsCompIdFixturesReviewRoute =
  DashboardContentCompetitionsCompIdFixturesReviewRouteImport.update({
    id: '/fixtures/review',
    path: '/fixtures/review',
    getParentRoute: () => DashboardContentCompetitionsCompIdRouteRoute,
  } as any)
const DashboardContentCompetitionsCompIdSettingsImagesRoute =
  DashboardContentCompetitionsCompIdSettingsImagesRouteImport.update({
    id: '/images',
    path: '/images',
    getParentRoute: () => DashboardContentCompetitionsCompIdSettingsRouteRoute,
  } as any)
const DashboardContentCompetitionsCompIdSettingsDivisionsRoute =
  DashboardContentCompetitionsCompIdSettingsDivisionsRouteImport.update({
    id: '/divisions',
    path: '/divisions',
    getParentRoute: () => DashboardContentCompetitionsCompIdSettingsRouteRoute,
  } as any)
const DashboardContentCompetitionsCompIdFixturesFixIdRouteRoute =
  DashboardContentCompetitionsCompIdFixturesFixIdRouteRouteImport.update({
    id: '/fixtures/$fixId',
    path: '/fixtures/$fixId',
    getParentRoute: () => DashboardContentCompetitionsCompIdRouteRoute,
  } as any)
const DashboardContentCompetitionsCompIdTeamsTeamIdIndexRoute =
  DashboardContentCompetitionsCompIdTeamsTeamIdIndexRouteImport.update({
    id: '/teams/$teamId/',
    path: '/teams/$teamId/',
    getParentRoute: () => DashboardContentCompetitionsCompIdRouteRoute,
  } as any)
const DashboardContentCompetitionsCompIdFixturesFixIdIndexRoute =
  DashboardContentCompetitionsCompIdFixturesFixIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      DashboardContentCompetitionsCompIdFixturesFixIdRouteRoute,
  } as any)
const DashboardContentCompetitionsCompIdPlayersPlayerIdEditRoute =
  DashboardContentCompetitionsCompIdPlayersPlayerIdEditRouteImport.update({
    id: '/players/$playerId/edit',
    path: '/players/$playerId/edit',
    getParentRoute: () => DashboardContentCompetitionsCompIdRouteRoute,
  } as any)
const DashboardContentCompetitionsCompIdFixturesFixIdReviewRoute =
  DashboardContentCompetitionsCompIdFixturesFixIdReviewRouteImport.update({
    id: '/review',
    path: '/review',
    getParentRoute: () =>
      DashboardContentCompetitionsCompIdFixturesFixIdRouteRoute,
  } as any)
const DashboardContentCompetitionsCompIdFixturesFixIdRawEventsRoute =
  DashboardContentCompetitionsCompIdFixturesFixIdRawEventsRouteImport.update({
    id: '/raw-events',
    path: '/raw-events',
    getParentRoute: () =>
      DashboardContentCompetitionsCompIdFixturesFixIdRouteRoute,
  } as any)
const DashboardContentCompetitionsCompIdFixturesFixIdPlayerStatsRoute =
  DashboardContentCompetitionsCompIdFixturesFixIdPlayerStatsRouteImport.update({
    id: '/player-stats',
    path: '/player-stats',
    getParentRoute: () =>
      DashboardContentCompetitionsCompIdFixturesFixIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/verify': typeof AuthVerifyRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/home/': typeof HomeIndexRoute
  '/competitions/$compId': typeof DashboardContentCompetitionsCompIdRouteRouteWithChildren
  '/agents/fixtures': typeof DashboardContentAgentsFixturesRoute
  '/admin/': typeof DashboardContentAdminIndexRoute
  '/agents/': typeof DashboardContentAgentsIndexRoute
  '/articles/': typeof DashboardContentArticlesIndexRoute
  '/competitions/': typeof DashboardContentCompetitionsIndexRoute
  '/players/': typeof DashboardContentPlayersIndexRoute
  '/teams/': typeof DashboardContentTeamsIndexRoute
  '/tickets/': typeof DashboardContentTicketsIndexRoute
  '/wallet/': typeof DashboardContentWalletIndexRoute
  '/competitions/$compId/stats': typeof DashboardContentCompetitionsCompIdStatsRouteRouteWithChildren
  '/articles/$articleId/edit': typeof DashboardContentArticlesArticleIdEditRoute
  '/articles/create/': typeof DashboardContentArticlesCreateIndexRoute
  '/competitions/$compId/fixtures/$fixId': typeof DashboardContentCompetitionsCompIdFixturesFixIdRouteRouteWithChildren
  '/competitions/$compId/divisions': typeof DashboardContentCompetitionsCompIdSettingsDivisionsRoute
  '/competitions/$compId/images': typeof DashboardContentCompetitionsCompIdSettingsImagesRoute
  '/competitions/$compId/fixtures/review': typeof DashboardContentCompetitionsCompIdFixturesReviewRoute
  '/competitions/$compId/players/create': typeof DashboardContentCompetitionsCompIdPlayersCreateRoute
  '/competitions/$compId/stats/teams': typeof DashboardContentCompetitionsCompIdStatsTeamsRoute
  '/competitions/$compId/': typeof DashboardContentCompetitionsCompIdSettingsIndexRoute
  '/competitions/$compId/fixtures/': typeof DashboardContentCompetitionsCompIdFixturesIndexRoute
  '/competitions/$compId/leagues/': typeof DashboardContentCompetitionsCompIdLeaguesIndexRoute
  '/competitions/$compId/players/': typeof DashboardContentCompetitionsCompIdPlayersIndexRoute
  '/competitions/$compId/stats/': typeof DashboardContentCompetitionsCompIdStatsIndexRoute
  '/competitions/$compId/teams/': typeof DashboardContentCompetitionsCompIdTeamsIndexRoute
  '/competitions/$compId/fixtures/$fixId/player-stats': typeof DashboardContentCompetitionsCompIdFixturesFixIdPlayerStatsRoute
  '/competitions/$compId/fixtures/$fixId/raw-events': typeof DashboardContentCompetitionsCompIdFixturesFixIdRawEventsRoute
  '/competitions/$compId/fixtures/$fixId/review': typeof DashboardContentCompetitionsCompIdFixturesFixIdReviewRoute
  '/competitions/$compId/players/$playerId/edit': typeof DashboardContentCompetitionsCompIdPlayersPlayerIdEditRoute
  '/competitions/$compId/fixtures/$fixId/': typeof DashboardContentCompetitionsCompIdFixturesFixIdIndexRoute
  '/competitions/$compId/teams/$teamId/': typeof DashboardContentCompetitionsCompIdTeamsTeamIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/verify': typeof AuthVerifyRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/home': typeof HomeIndexRoute
  '/competitions/$compId': typeof DashboardContentCompetitionsCompIdSettingsIndexRoute
  '/agents/fixtures': typeof DashboardContentAgentsFixturesRoute
  '/admin': typeof DashboardContentAdminIndexRoute
  '/agents': typeof DashboardContentAgentsIndexRoute
  '/articles': typeof DashboardContentArticlesIndexRoute
  '/competitions': typeof DashboardContentCompetitionsIndexRoute
  '/players': typeof DashboardContentPlayersIndexRoute
  '/teams': typeof DashboardContentTeamsIndexRoute
  '/tickets': typeof DashboardContentTicketsIndexRoute
  '/wallet': typeof DashboardContentWalletIndexRoute
  '/articles/$articleId/edit': typeof DashboardContentArticlesArticleIdEditRoute
  '/articles/create': typeof DashboardContentArticlesCreateIndexRoute
  '/competitions/$compId/divisions': typeof DashboardContentCompetitionsCompIdSettingsDivisionsRoute
  '/competitions/$compId/images': typeof DashboardContentCompetitionsCompIdSettingsImagesRoute
  '/competitions/$compId/fixtures/review': typeof DashboardContentCompetitionsCompIdFixturesReviewRoute
  '/competitions/$compId/players/create': typeof DashboardContentCompetitionsCompIdPlayersCreateRoute
  '/competitions/$compId/stats/teams': typeof DashboardContentCompetitionsCompIdStatsTeamsRoute
  '/competitions/$compId/fixtures': typeof DashboardContentCompetitionsCompIdFixturesIndexRoute
  '/competitions/$compId/leagues': typeof DashboardContentCompetitionsCompIdLeaguesIndexRoute
  '/competitions/$compId/players': typeof DashboardContentCompetitionsCompIdPlayersIndexRoute
  '/competitions/$compId/stats': typeof DashboardContentCompetitionsCompIdStatsIndexRoute
  '/competitions/$compId/teams': typeof DashboardContentCompetitionsCompIdTeamsIndexRoute
  '/competitions/$compId/fixtures/$fixId/player-stats': typeof DashboardContentCompetitionsCompIdFixturesFixIdPlayerStatsRoute
  '/competitions/$compId/fixtures/$fixId/raw-events': typeof DashboardContentCompetitionsCompIdFixturesFixIdRawEventsRoute
  '/competitions/$compId/fixtures/$fixId/review': typeof DashboardContentCompetitionsCompIdFixturesFixIdReviewRoute
  '/competitions/$compId/players/$playerId/edit': typeof DashboardContentCompetitionsCompIdPlayersPlayerIdEditRoute
  '/competitions/$compId/fixtures/$fixId': typeof DashboardContentCompetitionsCompIdFixturesFixIdIndexRoute
  '/competitions/$compId/teams/$teamId': typeof DashboardContentCompetitionsCompIdTeamsTeamIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_dashboard': typeof DashboardRouteRouteWithChildren
  '/_dashboard/_content': typeof DashboardContentRouteRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/verify': typeof AuthVerifyRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/home/': typeof HomeIndexRoute
  '/_dashboard/_content/competitions/$compId': typeof DashboardContentCompetitionsCompIdRouteRouteWithChildren
  '/_dashboard/_content/agents/fixtures': typeof DashboardContentAgentsFixturesRoute
  '/_dashboard/_content/admin/': typeof DashboardContentAdminIndexRoute
  '/_dashboard/_content/agents/': typeof DashboardContentAgentsIndexRoute
  '/_dashboard/_content/articles/': typeof DashboardContentArticlesIndexRoute
  '/_dashboard/_content/competitions/': typeof DashboardContentCompetitionsIndexRoute
  '/_dashboard/_content/players/': typeof DashboardContentPlayersIndexRoute
  '/_dashboard/_content/teams/': typeof DashboardContentTeamsIndexRoute
  '/_dashboard/_content/tickets/': typeof DashboardContentTicketsIndexRoute
  '/_dashboard/_content/wallet/': typeof DashboardContentWalletIndexRoute
  '/_dashboard/_content/competitions/$compId/_settings': typeof DashboardContentCompetitionsCompIdSettingsRouteRouteWithChildren
  '/_dashboard/_content/competitions/$compId/stats': typeof DashboardContentCompetitionsCompIdStatsRouteRouteWithChildren
  '/_dashboard/_content/articles/$articleId/edit': typeof DashboardContentArticlesArticleIdEditRoute
  '/_dashboard/_content/articles/create/': typeof DashboardContentArticlesCreateIndexRoute
  '/_dashboard/_content/competitions/$compId/fixtures/$fixId': typeof DashboardContentCompetitionsCompIdFixturesFixIdRouteRouteWithChildren
  '/_dashboard/_content/competitions/$compId/_settings/divisions': typeof DashboardContentCompetitionsCompIdSettingsDivisionsRoute
  '/_dashboard/_content/competitions/$compId/_settings/images': typeof DashboardContentCompetitionsCompIdSettingsImagesRoute
  '/_dashboard/_content/competitions/$compId/fixtures/review': typeof DashboardContentCompetitionsCompIdFixturesReviewRoute
  '/_dashboard/_content/competitions/$compId/players/create': typeof DashboardContentCompetitionsCompIdPlayersCreateRoute
  '/_dashboard/_content/competitions/$compId/stats/teams': typeof DashboardContentCompetitionsCompIdStatsTeamsRoute
  '/_dashboard/_content/competitions/$compId/_settings/': typeof DashboardContentCompetitionsCompIdSettingsIndexRoute
  '/_dashboard/_content/competitions/$compId/fixtures/': typeof DashboardContentCompetitionsCompIdFixturesIndexRoute
  '/_dashboard/_content/competitions/$compId/leagues/': typeof DashboardContentCompetitionsCompIdLeaguesIndexRoute
  '/_dashboard/_content/competitions/$compId/players/': typeof DashboardContentCompetitionsCompIdPlayersIndexRoute
  '/_dashboard/_content/competitions/$compId/stats/': typeof DashboardContentCompetitionsCompIdStatsIndexRoute
  '/_dashboard/_content/competitions/$compId/teams/': typeof DashboardContentCompetitionsCompIdTeamsIndexRoute
  '/_dashboard/_content/competitions/$compId/fixtures/$fixId/player-stats': typeof DashboardContentCompetitionsCompIdFixturesFixIdPlayerStatsRoute
  '/_dashboard/_content/competitions/$compId/fixtures/$fixId/raw-events': typeof DashboardContentCompetitionsCompIdFixturesFixIdRawEventsRoute
  '/_dashboard/_content/competitions/$compId/fixtures/$fixId/review': typeof DashboardContentCompetitionsCompIdFixturesFixIdReviewRoute
  '/_dashboard/_content/competitions/$compId/players/$playerId/edit': typeof DashboardContentCompetitionsCompIdPlayersPlayerIdEditRoute
  '/_dashboard/_content/competitions/$compId/fixtures/$fixId/': typeof DashboardContentCompetitionsCompIdFixturesFixIdIndexRoute
  '/_dashboard/_content/competitions/$compId/teams/$teamId/': typeof DashboardContentCompetitionsCompIdTeamsTeamIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify'
    | '/api/uploadthing'
    | '/home/'
    | '/competitions/$compId'
    | '/agents/fixtures'
    | '/admin/'
    | '/agents/'
    | '/articles/'
    | '/competitions/'
    | '/players/'
    | '/teams/'
    | '/tickets/'
    | '/wallet/'
    | '/competitions/$compId/stats'
    | '/articles/$articleId/edit'
    | '/articles/create/'
    | '/competitions/$compId/fixtures/$fixId'
    | '/competitions/$compId/divisions'
    | '/competitions/$compId/images'
    | '/competitions/$compId/fixtures/review'
    | '/competitions/$compId/players/create'
    | '/competitions/$compId/stats/teams'
    | '/competitions/$compId/'
    | '/competitions/$compId/fixtures/'
    | '/competitions/$compId/leagues/'
    | '/competitions/$compId/players/'
    | '/competitions/$compId/stats/'
    | '/competitions/$compId/teams/'
    | '/competitions/$compId/fixtures/$fixId/player-stats'
    | '/competitions/$compId/fixtures/$fixId/raw-events'
    | '/competitions/$compId/fixtures/$fixId/review'
    | '/competitions/$compId/players/$playerId/edit'
    | '/competitions/$compId/fixtures/$fixId/'
    | '/competitions/$compId/teams/$teamId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify'
    | '/api/uploadthing'
    | '/home'
    | '/competitions/$compId'
    | '/agents/fixtures'
    | '/admin'
    | '/agents'
    | '/articles'
    | '/competitions'
    | '/players'
    | '/teams'
    | '/tickets'
    | '/wallet'
    | '/articles/$articleId/edit'
    | '/articles/create'
    | '/competitions/$compId/divisions'
    | '/competitions/$compId/images'
    | '/competitions/$compId/fixtures/review'
    | '/competitions/$compId/players/create'
    | '/competitions/$compId/stats/teams'
    | '/competitions/$compId/fixtures'
    | '/competitions/$compId/leagues'
    | '/competitions/$compId/players'
    | '/competitions/$compId/stats'
    | '/competitions/$compId/teams'
    | '/competitions/$compId/fixtures/$fixId/player-stats'
    | '/competitions/$compId/fixtures/$fixId/raw-events'
    | '/competitions/$compId/fixtures/$fixId/review'
    | '/competitions/$compId/players/$playerId/edit'
    | '/competitions/$compId/fixtures/$fixId'
    | '/competitions/$compId/teams/$teamId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_dashboard'
    | '/_dashboard/_content'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/reset-password'
    | '/_auth/verify'
    | '/api/uploadthing'
    | '/home/'
    | '/_dashboard/_content/competitions/$compId'
    | '/_dashboard/_content/agents/fixtures'
    | '/_dashboard/_content/admin/'
    | '/_dashboard/_content/agents/'
    | '/_dashboard/_content/articles/'
    | '/_dashboard/_content/competitions/'
    | '/_dashboard/_content/players/'
    | '/_dashboard/_content/teams/'
    | '/_dashboard/_content/tickets/'
    | '/_dashboard/_content/wallet/'
    | '/_dashboard/_content/competitions/$compId/_settings'
    | '/_dashboard/_content/competitions/$compId/stats'
    | '/_dashboard/_content/articles/$articleId/edit'
    | '/_dashboard/_content/articles/create/'
    | '/_dashboard/_content/competitions/$compId/fixtures/$fixId'
    | '/_dashboard/_content/competitions/$compId/_settings/divisions'
    | '/_dashboard/_content/competitions/$compId/_settings/images'
    | '/_dashboard/_content/competitions/$compId/fixtures/review'
    | '/_dashboard/_content/competitions/$compId/players/create'
    | '/_dashboard/_content/competitions/$compId/stats/teams'
    | '/_dashboard/_content/competitions/$compId/_settings/'
    | '/_dashboard/_content/competitions/$compId/fixtures/'
    | '/_dashboard/_content/competitions/$compId/leagues/'
    | '/_dashboard/_content/competitions/$compId/players/'
    | '/_dashboard/_content/competitions/$compId/stats/'
    | '/_dashboard/_content/competitions/$compId/teams/'
    | '/_dashboard/_content/competitions/$compId/fixtures/$fixId/player-stats'
    | '/_dashboard/_content/competitions/$compId/fixtures/$fixId/raw-events'
    | '/_dashboard/_content/competitions/$compId/fixtures/$fixId/review'
    | '/_dashboard/_content/competitions/$compId/players/$playerId/edit'
    | '/_dashboard/_content/competitions/$compId/fixtures/$fixId/'
    | '/_dashboard/_content/competitions/$compId/teams/$teamId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  ApiUploadthingRoute: typeof ApiUploadthingRoute
  HomeIndexRoute: typeof HomeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploadthing': {
      id: '/api/uploadthing'
      path: '/api/uploadthing'
      fullPath: '/api/uploadthing'
      preLoaderRoute: typeof ApiUploadthingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/verify': {
      id: '/_auth/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_dashboard/_content': {
      id: '/_dashboard/_content'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardContentRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/_content/wallet/': {
      id: '/_dashboard/_content/wallet/'
      path: '/wallet'
      fullPath: '/wallet/'
      preLoaderRoute: typeof DashboardContentWalletIndexRouteImport
      parentRoute: typeof DashboardContentRouteRoute
    }
    '/_dashboard/_content/tickets/': {
      id: '/_dashboard/_content/tickets/'
      path: '/tickets'
      fullPath: '/tickets/'
      preLoaderRoute: typeof DashboardContentTicketsIndexRouteImport
      parentRoute: typeof DashboardContentRouteRoute
    }
    '/_dashboard/_content/teams/': {
      id: '/_dashboard/_content/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof DashboardContentTeamsIndexRouteImport
      parentRoute: typeof DashboardContentRouteRoute
    }
    '/_dashboard/_content/players/': {
      id: '/_dashboard/_content/players/'
      path: '/players'
      fullPath: '/players/'
      preLoaderRoute: typeof DashboardContentPlayersIndexRouteImport
      parentRoute: typeof DashboardContentRouteRoute
    }
    '/_dashboard/_content/competitions/': {
      id: '/_dashboard/_content/competitions/'
      path: '/competitions'
      fullPath: '/competitions/'
      preLoaderRoute: typeof DashboardContentCompetitionsIndexRouteImport
      parentRoute: typeof DashboardContentRouteRoute
    }
    '/_dashboard/_content/articles/': {
      id: '/_dashboard/_content/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof DashboardContentArticlesIndexRouteImport
      parentRoute: typeof DashboardContentRouteRoute
    }
    '/_dashboard/_content/agents/': {
      id: '/_dashboard/_content/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof DashboardContentAgentsIndexRouteImport
      parentRoute: typeof DashboardContentRouteRoute
    }
    '/_dashboard/_content/admin/': {
      id: '/_dashboard/_content/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof DashboardContentAdminIndexRouteImport
      parentRoute: typeof DashboardContentRouteRoute
    }
    '/_dashboard/_content/agents/fixtures': {
      id: '/_dashboard/_content/agents/fixtures'
      path: '/agents/fixtures'
      fullPath: '/agents/fixtures'
      preLoaderRoute: typeof DashboardContentAgentsFixturesRouteImport
      parentRoute: typeof DashboardContentRouteRoute
    }
    '/_dashboard/_content/competitions/$compId': {
      id: '/_dashboard/_content/competitions/$compId'
      path: '/competitions/$compId'
      fullPath: '/competitions/$compId'
      preLoaderRoute: typeof DashboardContentCompetitionsCompIdRouteRouteImport
      parentRoute: typeof DashboardContentRouteRoute
    }
    '/_dashboard/_content/articles/create/': {
      id: '/_dashboard/_content/articles/create/'
      path: '/articles/create'
      fullPath: '/articles/create/'
      preLoaderRoute: typeof DashboardContentArticlesCreateIndexRouteImport
      parentRoute: typeof DashboardContentRouteRoute
    }
    '/_dashboard/_content/articles/$articleId/edit': {
      id: '/_dashboard/_content/articles/$articleId/edit'
      path: '/articles/$articleId/edit'
      fullPath: '/articles/$articleId/edit'
      preLoaderRoute: typeof DashboardContentArticlesArticleIdEditRouteImport
      parentRoute: typeof DashboardContentRouteRoute
    }
    '/_dashboard/_content/competitions/$compId/stats': {
      id: '/_dashboard/_content/competitions/$compId/stats'
      path: '/stats'
      fullPath: '/competitions/$compId/stats'
      preLoaderRoute: typeof DashboardContentCompetitionsCompIdStatsRouteRouteImport
      parentRoute: typeof DashboardContentCompetitionsCompIdRouteRoute
    }
    '/_dashboard/_content/competitions/$compId/_settings': {
      id: '/_dashboard/_content/competitions/$compId/_settings'
      path: ''
      fullPath: '/competitions/$compId'
      preLoaderRoute: typeof DashboardContentCompetitionsCompIdSettingsRouteRouteImport
      parentRoute: typeof DashboardContentCompetitionsCompIdRouteRoute
    }
    '/_dashboard/_content/competitions/$compId/teams/': {
      id: '/_dashboard/_content/competitions/$compId/teams/'
      path: '/teams'
      fullPath: '/competitions/$compId/teams/'
      preLoaderRoute: typeof DashboardContentCompetitionsCompIdTeamsIndexRouteImport
      parentRoute: typeof DashboardContentCompetitionsCompIdRouteRoute
    }
    '/_dashboard/_content/competitions/$compId/stats/': {
      id: '/_dashboard/_content/competitions/$compId/stats/'
      path: '/'
      fullPath: '/competitions/$compId/stats/'
      preLoaderRoute: typeof DashboardContentCompetitionsCompIdStatsIndexRouteImport
      parentRoute: typeof DashboardContentCompetitionsCompIdStatsRouteRoute
    }
    '/_dashboard/_content/competitions/$compId/players/': {
      id: '/_dashboard/_content/competitions/$compId/players/'
      path: '/players'
      fullPath: '/competitions/$compId/players/'
      preLoaderRoute: typeof DashboardContentCompetitionsCompIdPlayersIndexRouteImport
      parentRoute: typeof DashboardContentCompetitionsCompIdRouteRoute
    }
    '/_dashboard/_content/competitions/$compId/leagues/': {
      id: '/_dashboard/_content/competitions/$compId/leagues/'
      path: '/leagues'
      fullPath: '/competitions/$compId/leagues/'
      preLoaderRoute: typeof DashboardContentCompetitionsCompIdLeaguesIndexRouteImport
      parentRoute: typeof DashboardContentCompetitionsCompIdRouteRoute
    }
    '/_dashboard/_content/competitions/$compId/fixtures/': {
      id: '/_dashboard/_content/competitions/$compId/fixtures/'
      path: '/fixtures'
      fullPath: '/competitions/$compId/fixtures/'
      preLoaderRoute: typeof DashboardContentCompetitionsCompIdFixturesIndexRouteImport
      parentRoute: typeof DashboardContentCompetitionsCompIdRouteRoute
    }
    '/_dashboard/_content/competitions/$compId/_settings/': {
      id: '/_dashboard/_content/competitions/$compId/_settings/'
      path: '/'
      fullPath: '/competitions/$compId/'
      preLoaderRoute: typeof DashboardContentCompetitionsCompIdSettingsIndexRouteImport
      parentRoute: typeof DashboardContentCompetitionsCompIdSettingsRouteRoute
    }
    '/_dashboard/_content/competitions/$compId/stats/teams': {
      id: '/_dashboard/_content/competitions/$compId/stats/teams'
      path: '/teams'
      fullPath: '/competitions/$compId/stats/teams'
      preLoaderRoute: typeof DashboardContentCompetitionsCompIdStatsTeamsRouteImport
      parentRoute: typeof DashboardContentCompetitionsCompIdStatsRouteRoute
    }
    '/_dashboard/_content/competitions/$compId/players/create': {
      id: '/_dashboard/_content/competitions/$compId/players/create'
      path: '/players/create'
      fullPath: '/competitions/$compId/players/create'
      preLoaderRoute: typeof DashboardContentCompetitionsCompIdPlayersCreateRouteImport
      parentRoute: typeof DashboardContentCompetitionsCompIdRouteRoute
    }
    '/_dashboard/_content/competitions/$compId/fixtures/review': {
      id: '/_dashboard/_content/competitions/$compId/fixtures/review'
      path: '/fixtures/review'
      fullPath: '/competitions/$compId/fixtures/review'
      preLoaderRoute: typeof DashboardContentCompetitionsCompIdFixturesReviewRouteImport
      parentRoute: typeof DashboardContentCompetitionsCompIdRouteRoute
    }
    '/_dashboard/_content/competitions/$compId/_settings/images': {
      id: '/_dashboard/_content/competitions/$compId/_settings/images'
      path: '/images'
      fullPath: '/competitions/$compId/images'
      preLoaderRoute: typeof DashboardContentCompetitionsCompIdSettingsImagesRouteImport
      parentRoute: typeof DashboardContentCompetitionsCompIdSettingsRouteRoute
    }
    '/_dashboard/_content/competitions/$compId/_settings/divisions': {
      id: '/_dashboard/_content/competitions/$compId/_settings/divisions'
      path: '/divisions'
      fullPath: '/competitions/$compId/divisions'
      preLoaderRoute: typeof DashboardContentCompetitionsCompIdSettingsDivisionsRouteImport
      parentRoute: typeof DashboardContentCompetitionsCompIdSettingsRouteRoute
    }
    '/_dashboard/_content/competitions/$compId/fixtures/$fixId': {
      id: '/_dashboard/_content/competitions/$compId/fixtures/$fixId'
      path: '/fixtures/$fixId'
      fullPath: '/competitions/$compId/fixtures/$fixId'
      preLoaderRoute: typeof DashboardContentCompetitionsCompIdFixturesFixIdRouteRouteImport
      parentRoute: typeof DashboardContentCompetitionsCompIdRouteRoute
    }
    '/_dashboard/_content/competitions/$compId/teams/$teamId/': {
      id: '/_dashboard/_content/competitions/$compId/teams/$teamId/'
      path: '/teams/$teamId'
      fullPath: '/competitions/$compId/teams/$teamId/'
      preLoaderRoute: typeof DashboardContentCompetitionsCompIdTeamsTeamIdIndexRouteImport
      parentRoute: typeof DashboardContentCompetitionsCompIdRouteRoute
    }
    '/_dashboard/_content/competitions/$compId/fixtures/$fixId/': {
      id: '/_dashboard/_content/competitions/$compId/fixtures/$fixId/'
      path: '/'
      fullPath: '/competitions/$compId/fixtures/$fixId/'
      preLoaderRoute: typeof DashboardContentCompetitionsCompIdFixturesFixIdIndexRouteImport
      parentRoute: typeof DashboardContentCompetitionsCompIdFixturesFixIdRouteRoute
    }
    '/_dashboard/_content/competitions/$compId/players/$playerId/edit': {
      id: '/_dashboard/_content/competitions/$compId/players/$playerId/edit'
      path: '/players/$playerId/edit'
      fullPath: '/competitions/$compId/players/$playerId/edit'
      preLoaderRoute: typeof DashboardContentCompetitionsCompIdPlayersPlayerIdEditRouteImport
      parentRoute: typeof DashboardContentCompetitionsCompIdRouteRoute
    }
    '/_dashboard/_content/competitions/$compId/fixtures/$fixId/review': {
      id: '/_dashboard/_content/competitions/$compId/fixtures/$fixId/review'
      path: '/review'
      fullPath: '/competitions/$compId/fixtures/$fixId/review'
      preLoaderRoute: typeof DashboardContentCompetitionsCompIdFixturesFixIdReviewRouteImport
      parentRoute: typeof DashboardContentCompetitionsCompIdFixturesFixIdRouteRoute
    }
    '/_dashboard/_content/competitions/$compId/fixtures/$fixId/raw-events': {
      id: '/_dashboard/_content/competitions/$compId/fixtures/$fixId/raw-events'
      path: '/raw-events'
      fullPath: '/competitions/$compId/fixtures/$fixId/raw-events'
      preLoaderRoute: typeof DashboardContentCompetitionsCompIdFixturesFixIdRawEventsRouteImport
      parentRoute: typeof DashboardContentCompetitionsCompIdFixturesFixIdRouteRoute
    }
    '/_dashboard/_content/competitions/$compId/fixtures/$fixId/player-stats': {
      id: '/_dashboard/_content/competitions/$compId/fixtures/$fixId/player-stats'
      path: '/player-stats'
      fullPath: '/competitions/$compId/fixtures/$fixId/player-stats'
      preLoaderRoute: typeof DashboardContentCompetitionsCompIdFixturesFixIdPlayerStatsRouteImport
      parentRoute: typeof DashboardContentCompetitionsCompIdFixturesFixIdRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthVerifyRoute: AuthVerifyRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface DashboardContentCompetitionsCompIdSettingsRouteRouteChildren {
  DashboardContentCompetitionsCompIdSettingsDivisionsRoute: typeof DashboardContentCompetitionsCompIdSettingsDivisionsRoute
  DashboardContentCompetitionsCompIdSettingsImagesRoute: typeof DashboardContentCompetitionsCompIdSettingsImagesRoute
  DashboardContentCompetitionsCompIdSettingsIndexRoute: typeof DashboardContentCompetitionsCompIdSettingsIndexRoute
}

const DashboardContentCompetitionsCompIdSettingsRouteRouteChildren: DashboardContentCompetitionsCompIdSettingsRouteRouteChildren =
  {
    DashboardContentCompetitionsCompIdSettingsDivisionsRoute:
      DashboardContentCompetitionsCompIdSettingsDivisionsRoute,
    DashboardContentCompetitionsCompIdSettingsImagesRoute:
      DashboardContentCompetitionsCompIdSettingsImagesRoute,
    DashboardContentCompetitionsCompIdSettingsIndexRoute:
      DashboardContentCompetitionsCompIdSettingsIndexRoute,
  }

const DashboardContentCompetitionsCompIdSettingsRouteRouteWithChildren =
  DashboardContentCompetitionsCompIdSettingsRouteRoute._addFileChildren(
    DashboardContentCompetitionsCompIdSettingsRouteRouteChildren,
  )

interface DashboardContentCompetitionsCompIdStatsRouteRouteChildren {
  DashboardContentCompetitionsCompIdStatsTeamsRoute: typeof DashboardContentCompetitionsCompIdStatsTeamsRoute
  DashboardContentCompetitionsCompIdStatsIndexRoute: typeof DashboardContentCompetitionsCompIdStatsIndexRoute
}

const DashboardContentCompetitionsCompIdStatsRouteRouteChildren: DashboardContentCompetitionsCompIdStatsRouteRouteChildren =
  {
    DashboardContentCompetitionsCompIdStatsTeamsRoute:
      DashboardContentCompetitionsCompIdStatsTeamsRoute,
    DashboardContentCompetitionsCompIdStatsIndexRoute:
      DashboardContentCompetitionsCompIdStatsIndexRoute,
  }

const DashboardContentCompetitionsCompIdStatsRouteRouteWithChildren =
  DashboardContentCompetitionsCompIdStatsRouteRoute._addFileChildren(
    DashboardContentCompetitionsCompIdStatsRouteRouteChildren,
  )

interface DashboardContentCompetitionsCompIdFixturesFixIdRouteRouteChildren {
  DashboardContentCompetitionsCompIdFixturesFixIdPlayerStatsRoute: typeof DashboardContentCompetitionsCompIdFixturesFixIdPlayerStatsRoute
  DashboardContentCompetitionsCompIdFixturesFixIdRawEventsRoute: typeof DashboardContentCompetitionsCompIdFixturesFixIdRawEventsRoute
  DashboardContentCompetitionsCompIdFixturesFixIdReviewRoute: typeof DashboardContentCompetitionsCompIdFixturesFixIdReviewRoute
  DashboardContentCompetitionsCompIdFixturesFixIdIndexRoute: typeof DashboardContentCompetitionsCompIdFixturesFixIdIndexRoute
}

const DashboardContentCompetitionsCompIdFixturesFixIdRouteRouteChildren: DashboardContentCompetitionsCompIdFixturesFixIdRouteRouteChildren =
  {
    DashboardContentCompetitionsCompIdFixturesFixIdPlayerStatsRoute:
      DashboardContentCompetitionsCompIdFixturesFixIdPlayerStatsRoute,
    DashboardContentCompetitionsCompIdFixturesFixIdRawEventsRoute:
      DashboardContentCompetitionsCompIdFixturesFixIdRawEventsRoute,
    DashboardContentCompetitionsCompIdFixturesFixIdReviewRoute:
      DashboardContentCompetitionsCompIdFixturesFixIdReviewRoute,
    DashboardContentCompetitionsCompIdFixturesFixIdIndexRoute:
      DashboardContentCompetitionsCompIdFixturesFixIdIndexRoute,
  }

const DashboardContentCompetitionsCompIdFixturesFixIdRouteRouteWithChildren =
  DashboardContentCompetitionsCompIdFixturesFixIdRouteRoute._addFileChildren(
    DashboardContentCompetitionsCompIdFixturesFixIdRouteRouteChildren,
  )

interface DashboardContentCompetitionsCompIdRouteRouteChildren {
  DashboardContentCompetitionsCompIdSettingsRouteRoute: typeof DashboardContentCompetitionsCompIdSettingsRouteRouteWithChildren
  DashboardContentCompetitionsCompIdStatsRouteRoute: typeof DashboardContentCompetitionsCompIdStatsRouteRouteWithChildren
  DashboardContentCompetitionsCompIdFixturesFixIdRouteRoute: typeof DashboardContentCompetitionsCompIdFixturesFixIdRouteRouteWithChildren
  DashboardContentCompetitionsCompIdFixturesReviewRoute: typeof DashboardContentCompetitionsCompIdFixturesReviewRoute
  DashboardContentCompetitionsCompIdPlayersCreateRoute: typeof DashboardContentCompetitionsCompIdPlayersCreateRoute
  DashboardContentCompetitionsCompIdFixturesIndexRoute: typeof DashboardContentCompetitionsCompIdFixturesIndexRoute
  DashboardContentCompetitionsCompIdLeaguesIndexRoute: typeof DashboardContentCompetitionsCompIdLeaguesIndexRoute
  DashboardContentCompetitionsCompIdPlayersIndexRoute: typeof DashboardContentCompetitionsCompIdPlayersIndexRoute
  DashboardContentCompetitionsCompIdTeamsIndexRoute: typeof DashboardContentCompetitionsCompIdTeamsIndexRoute
  DashboardContentCompetitionsCompIdPlayersPlayerIdEditRoute: typeof DashboardContentCompetitionsCompIdPlayersPlayerIdEditRoute
  DashboardContentCompetitionsCompIdTeamsTeamIdIndexRoute: typeof DashboardContentCompetitionsCompIdTeamsTeamIdIndexRoute
}

const DashboardContentCompetitionsCompIdRouteRouteChildren: DashboardContentCompetitionsCompIdRouteRouteChildren =
  {
    DashboardContentCompetitionsCompIdSettingsRouteRoute:
      DashboardContentCompetitionsCompIdSettingsRouteRouteWithChildren,
    DashboardContentCompetitionsCompIdStatsRouteRoute:
      DashboardContentCompetitionsCompIdStatsRouteRouteWithChildren,
    DashboardContentCompetitionsCompIdFixturesFixIdRouteRoute:
      DashboardContentCompetitionsCompIdFixturesFixIdRouteRouteWithChildren,
    DashboardContentCompetitionsCompIdFixturesReviewRoute:
      DashboardContentCompetitionsCompIdFixturesReviewRoute,
    DashboardContentCompetitionsCompIdPlayersCreateRoute:
      DashboardContentCompetitionsCompIdPlayersCreateRoute,
    DashboardContentCompetitionsCompIdFixturesIndexRoute:
      DashboardContentCompetitionsCompIdFixturesIndexRoute,
    DashboardContentCompetitionsCompIdLeaguesIndexRoute:
      DashboardContentCompetitionsCompIdLeaguesIndexRoute,
    DashboardContentCompetitionsCompIdPlayersIndexRoute:
      DashboardContentCompetitionsCompIdPlayersIndexRoute,
    DashboardContentCompetitionsCompIdTeamsIndexRoute:
      DashboardContentCompetitionsCompIdTeamsIndexRoute,
    DashboardContentCompetitionsCompIdPlayersPlayerIdEditRoute:
      DashboardContentCompetitionsCompIdPlayersPlayerIdEditRoute,
    DashboardContentCompetitionsCompIdTeamsTeamIdIndexRoute:
      DashboardContentCompetitionsCompIdTeamsTeamIdIndexRoute,
  }

const DashboardContentCompetitionsCompIdRouteRouteWithChildren =
  DashboardContentCompetitionsCompIdRouteRoute._addFileChildren(
    DashboardContentCompetitionsCompIdRouteRouteChildren,
  )

interface DashboardContentRouteRouteChildren {
  DashboardContentCompetitionsCompIdRouteRoute: typeof DashboardContentCompetitionsCompIdRouteRouteWithChildren
  DashboardContentAgentsFixturesRoute: typeof DashboardContentAgentsFixturesRoute
  DashboardContentAdminIndexRoute: typeof DashboardContentAdminIndexRoute
  DashboardContentAgentsIndexRoute: typeof DashboardContentAgentsIndexRoute
  DashboardContentArticlesIndexRoute: typeof DashboardContentArticlesIndexRoute
  DashboardContentCompetitionsIndexRoute: typeof DashboardContentCompetitionsIndexRoute
  DashboardContentPlayersIndexRoute: typeof DashboardContentPlayersIndexRoute
  DashboardContentTeamsIndexRoute: typeof DashboardContentTeamsIndexRoute
  DashboardContentTicketsIndexRoute: typeof DashboardContentTicketsIndexRoute
  DashboardContentWalletIndexRoute: typeof DashboardContentWalletIndexRoute
  DashboardContentArticlesArticleIdEditRoute: typeof DashboardContentArticlesArticleIdEditRoute
  DashboardContentArticlesCreateIndexRoute: typeof DashboardContentArticlesCreateIndexRoute
}

const DashboardContentRouteRouteChildren: DashboardContentRouteRouteChildren = {
  DashboardContentCompetitionsCompIdRouteRoute:
    DashboardContentCompetitionsCompIdRouteRouteWithChildren,
  DashboardContentAgentsFixturesRoute: DashboardContentAgentsFixturesRoute,
  DashboardContentAdminIndexRoute: DashboardContentAdminIndexRoute,
  DashboardContentAgentsIndexRoute: DashboardContentAgentsIndexRoute,
  DashboardContentArticlesIndexRoute: DashboardContentArticlesIndexRoute,
  DashboardContentCompetitionsIndexRoute:
    DashboardContentCompetitionsIndexRoute,
  DashboardContentPlayersIndexRoute: DashboardContentPlayersIndexRoute,
  DashboardContentTeamsIndexRoute: DashboardContentTeamsIndexRoute,
  DashboardContentTicketsIndexRoute: DashboardContentTicketsIndexRoute,
  DashboardContentWalletIndexRoute: DashboardContentWalletIndexRoute,
  DashboardContentArticlesArticleIdEditRoute:
    DashboardContentArticlesArticleIdEditRoute,
  DashboardContentArticlesCreateIndexRoute:
    DashboardContentArticlesCreateIndexRoute,
}

const DashboardContentRouteRouteWithChildren =
  DashboardContentRouteRoute._addFileChildren(
    DashboardContentRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardContentRouteRoute: typeof DashboardContentRouteRouteWithChildren
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardContentRouteRoute: DashboardContentRouteRouteWithChildren,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  ApiUploadthingRoute: ApiUploadthingRoute,
  HomeIndexRoute: HomeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
