/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/_dashboard/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as ApiUploadthingRouteImport } from './routes/api/uploadthing'
import { Route as AuthVerifyRouteImport } from './routes/_auth/verify'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as DashboardWalletIndexRouteImport } from './routes/_dashboard/wallet/index'
import { Route as DashboardTicketsIndexRouteImport } from './routes/_dashboard/tickets/index'
import { Route as DashboardTeamsIndexRouteImport } from './routes/_dashboard/teams/index'
import { Route as DashboardPlayersIndexRouteImport } from './routes/_dashboard/players/index'
import { Route as DashboardCompetitionsIndexRouteImport } from './routes/_dashboard/competitions/index'
import { Route as DashboardArticlesIndexRouteImport } from './routes/_dashboard/articles/index'
import { Route as DashboardAgentsIndexRouteImport } from './routes/_dashboard/agents/index'
import { Route as DashboardAdminIndexRouteImport } from './routes/_dashboard/admin/index'
import { Route as DashboardAgentsFixturesRouteImport } from './routes/_dashboard/agents/fixtures'
import { Route as DashboardCompetitionsStatsRouteRouteImport } from './routes/_dashboard/competitions/stats/route'
import { Route as DashboardCompetitionsTeamsIndexRouteImport } from './routes/_dashboard/competitions/teams/index'
import { Route as DashboardCompetitionsStatsIndexRouteImport } from './routes/_dashboard/competitions/stats/index'
import { Route as DashboardCompetitionsPlayersIndexRouteImport } from './routes/_dashboard/competitions/players/index'
import { Route as DashboardCompetitionsLeaguesIndexRouteImport } from './routes/_dashboard/competitions/leagues/index'
import { Route as DashboardCompetitionsFixturesIndexRouteImport } from './routes/_dashboard/competitions/fixtures/index'
import { Route as DashboardArticlesCreateIndexRouteImport } from './routes/_dashboard/articles/create/index'
import { Route as DashboardCompetitionsStatsTeamsRouteImport } from './routes/_dashboard/competitions/stats/teams'
import { Route as DashboardCompetitionsPlayersCreateRouteImport } from './routes/_dashboard/competitions/players/create'
import { Route as DashboardCompetitionsFixturesReviewRouteImport } from './routes/_dashboard/competitions/fixtures/review'
import { Route as DashboardArticlesArticleIdEditRouteImport } from './routes/_dashboard/articles/$articleId/edit'
import { Route as DashboardCompetitionsFixturesFixIdRouteRouteImport } from './routes/_dashboard/competitions/fixtures/$fixId/route'
import { Route as DashboardCompetitionsFixturesFixIdIndexRouteImport } from './routes/_dashboard/competitions/fixtures/$fixId/index'
import { Route as DashboardCompetitionsPlayersPlayerIdEditRouteImport } from './routes/_dashboard/competitions/players/$playerId/edit'
import { Route as DashboardCompetitionsFixturesFixIdReviewRouteImport } from './routes/_dashboard/competitions/fixtures/$fixId/review'
import { Route as DashboardCompetitionsFixturesFixIdRawEventsRouteImport } from './routes/_dashboard/competitions/fixtures/$fixId/raw-events'
import { Route as DashboardCompetitionsFixturesFixIdPlayerStatsRouteImport } from './routes/_dashboard/competitions/fixtures/$fixId/player-stats'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadthingRoute = ApiUploadthingRouteImport.update({
  id: '/api/uploadthing',
  path: '/api/uploadthing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const DashboardWalletIndexRoute = DashboardWalletIndexRouteImport.update({
  id: '/wallet/',
  path: '/wallet/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTicketsIndexRoute = DashboardTicketsIndexRouteImport.update({
  id: '/tickets/',
  path: '/tickets/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTeamsIndexRoute = DashboardTeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPlayersIndexRoute = DashboardPlayersIndexRouteImport.update({
  id: '/players/',
  path: '/players/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCompetitionsIndexRoute =
  DashboardCompetitionsIndexRouteImport.update({
    id: '/competitions/',
    path: '/competitions/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardArticlesIndexRoute = DashboardArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAgentsIndexRoute = DashboardAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAgentsFixturesRoute = DashboardAgentsFixturesRouteImport.update({
  id: '/agents/fixtures',
  path: '/agents/fixtures',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCompetitionsStatsRouteRoute =
  DashboardCompetitionsStatsRouteRouteImport.update({
    id: '/competitions/stats',
    path: '/competitions/stats',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardCompetitionsTeamsIndexRoute =
  DashboardCompetitionsTeamsIndexRouteImport.update({
    id: '/competitions/teams/',
    path: '/competitions/teams/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardCompetitionsStatsIndexRoute =
  DashboardCompetitionsStatsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardCompetitionsStatsRouteRoute,
  } as any)
const DashboardCompetitionsPlayersIndexRoute =
  DashboardCompetitionsPlayersIndexRouteImport.update({
    id: '/competitions/players/',
    path: '/competitions/players/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardCompetitionsLeaguesIndexRoute =
  DashboardCompetitionsLeaguesIndexRouteImport.update({
    id: '/competitions/leagues/',
    path: '/competitions/leagues/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardCompetitionsFixturesIndexRoute =
  DashboardCompetitionsFixturesIndexRouteImport.update({
    id: '/competitions/fixtures/',
    path: '/competitions/fixtures/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardArticlesCreateIndexRoute =
  DashboardArticlesCreateIndexRouteImport.update({
    id: '/articles/create/',
    path: '/articles/create/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardCompetitionsStatsTeamsRoute =
  DashboardCompetitionsStatsTeamsRouteImport.update({
    id: '/teams',
    path: '/teams',
    getParentRoute: () => DashboardCompetitionsStatsRouteRoute,
  } as any)
const DashboardCompetitionsPlayersCreateRoute =
  DashboardCompetitionsPlayersCreateRouteImport.update({
    id: '/competitions/players/create',
    path: '/competitions/players/create',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardCompetitionsFixturesReviewRoute =
  DashboardCompetitionsFixturesReviewRouteImport.update({
    id: '/competitions/fixtures/review',
    path: '/competitions/fixtures/review',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardArticlesArticleIdEditRoute =
  DashboardArticlesArticleIdEditRouteImport.update({
    id: '/articles/$articleId/edit',
    path: '/articles/$articleId/edit',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardCompetitionsFixturesFixIdRouteRoute =
  DashboardCompetitionsFixturesFixIdRouteRouteImport.update({
    id: '/competitions/fixtures/$fixId',
    path: '/competitions/fixtures/$fixId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardCompetitionsFixturesFixIdIndexRoute =
  DashboardCompetitionsFixturesFixIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardCompetitionsFixturesFixIdRouteRoute,
  } as any)
const DashboardCompetitionsPlayersPlayerIdEditRoute =
  DashboardCompetitionsPlayersPlayerIdEditRouteImport.update({
    id: '/competitions/players/$playerId/edit',
    path: '/competitions/players/$playerId/edit',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardCompetitionsFixturesFixIdReviewRoute =
  DashboardCompetitionsFixturesFixIdReviewRouteImport.update({
    id: '/review',
    path: '/review',
    getParentRoute: () => DashboardCompetitionsFixturesFixIdRouteRoute,
  } as any)
const DashboardCompetitionsFixturesFixIdRawEventsRoute =
  DashboardCompetitionsFixturesFixIdRawEventsRouteImport.update({
    id: '/raw-events',
    path: '/raw-events',
    getParentRoute: () => DashboardCompetitionsFixturesFixIdRouteRoute,
  } as any)
const DashboardCompetitionsFixturesFixIdPlayerStatsRoute =
  DashboardCompetitionsFixturesFixIdPlayerStatsRouteImport.update({
    id: '/player-stats',
    path: '/player-stats',
    getParentRoute: () => DashboardCompetitionsFixturesFixIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/verify': typeof AuthVerifyRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/home/': typeof HomeIndexRoute
  '/competitions/stats': typeof DashboardCompetitionsStatsRouteRouteWithChildren
  '/agents/fixtures': typeof DashboardAgentsFixturesRoute
  '/admin/': typeof DashboardAdminIndexRoute
  '/agents/': typeof DashboardAgentsIndexRoute
  '/articles/': typeof DashboardArticlesIndexRoute
  '/competitions/': typeof DashboardCompetitionsIndexRoute
  '/players/': typeof DashboardPlayersIndexRoute
  '/teams/': typeof DashboardTeamsIndexRoute
  '/tickets/': typeof DashboardTicketsIndexRoute
  '/wallet/': typeof DashboardWalletIndexRoute
  '/competitions/fixtures/$fixId': typeof DashboardCompetitionsFixturesFixIdRouteRouteWithChildren
  '/articles/$articleId/edit': typeof DashboardArticlesArticleIdEditRoute
  '/competitions/fixtures/review': typeof DashboardCompetitionsFixturesReviewRoute
  '/competitions/players/create': typeof DashboardCompetitionsPlayersCreateRoute
  '/competitions/stats/teams': typeof DashboardCompetitionsStatsTeamsRoute
  '/articles/create/': typeof DashboardArticlesCreateIndexRoute
  '/competitions/fixtures/': typeof DashboardCompetitionsFixturesIndexRoute
  '/competitions/leagues/': typeof DashboardCompetitionsLeaguesIndexRoute
  '/competitions/players/': typeof DashboardCompetitionsPlayersIndexRoute
  '/competitions/stats/': typeof DashboardCompetitionsStatsIndexRoute
  '/competitions/teams/': typeof DashboardCompetitionsTeamsIndexRoute
  '/competitions/fixtures/$fixId/player-stats': typeof DashboardCompetitionsFixturesFixIdPlayerStatsRoute
  '/competitions/fixtures/$fixId/raw-events': typeof DashboardCompetitionsFixturesFixIdRawEventsRoute
  '/competitions/fixtures/$fixId/review': typeof DashboardCompetitionsFixturesFixIdReviewRoute
  '/competitions/players/$playerId/edit': typeof DashboardCompetitionsPlayersPlayerIdEditRoute
  '/competitions/fixtures/$fixId/': typeof DashboardCompetitionsFixturesFixIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/verify': typeof AuthVerifyRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/home': typeof HomeIndexRoute
  '/agents/fixtures': typeof DashboardAgentsFixturesRoute
  '/admin': typeof DashboardAdminIndexRoute
  '/agents': typeof DashboardAgentsIndexRoute
  '/articles': typeof DashboardArticlesIndexRoute
  '/competitions': typeof DashboardCompetitionsIndexRoute
  '/players': typeof DashboardPlayersIndexRoute
  '/teams': typeof DashboardTeamsIndexRoute
  '/tickets': typeof DashboardTicketsIndexRoute
  '/wallet': typeof DashboardWalletIndexRoute
  '/articles/$articleId/edit': typeof DashboardArticlesArticleIdEditRoute
  '/competitions/fixtures/review': typeof DashboardCompetitionsFixturesReviewRoute
  '/competitions/players/create': typeof DashboardCompetitionsPlayersCreateRoute
  '/competitions/stats/teams': typeof DashboardCompetitionsStatsTeamsRoute
  '/articles/create': typeof DashboardArticlesCreateIndexRoute
  '/competitions/fixtures': typeof DashboardCompetitionsFixturesIndexRoute
  '/competitions/leagues': typeof DashboardCompetitionsLeaguesIndexRoute
  '/competitions/players': typeof DashboardCompetitionsPlayersIndexRoute
  '/competitions/stats': typeof DashboardCompetitionsStatsIndexRoute
  '/competitions/teams': typeof DashboardCompetitionsTeamsIndexRoute
  '/competitions/fixtures/$fixId/player-stats': typeof DashboardCompetitionsFixturesFixIdPlayerStatsRoute
  '/competitions/fixtures/$fixId/raw-events': typeof DashboardCompetitionsFixturesFixIdRawEventsRoute
  '/competitions/fixtures/$fixId/review': typeof DashboardCompetitionsFixturesFixIdReviewRoute
  '/competitions/players/$playerId/edit': typeof DashboardCompetitionsPlayersPlayerIdEditRoute
  '/competitions/fixtures/$fixId': typeof DashboardCompetitionsFixturesFixIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_dashboard': typeof DashboardRouteRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/verify': typeof AuthVerifyRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/home/': typeof HomeIndexRoute
  '/_dashboard/competitions/stats': typeof DashboardCompetitionsStatsRouteRouteWithChildren
  '/_dashboard/agents/fixtures': typeof DashboardAgentsFixturesRoute
  '/_dashboard/admin/': typeof DashboardAdminIndexRoute
  '/_dashboard/agents/': typeof DashboardAgentsIndexRoute
  '/_dashboard/articles/': typeof DashboardArticlesIndexRoute
  '/_dashboard/competitions/': typeof DashboardCompetitionsIndexRoute
  '/_dashboard/players/': typeof DashboardPlayersIndexRoute
  '/_dashboard/teams/': typeof DashboardTeamsIndexRoute
  '/_dashboard/tickets/': typeof DashboardTicketsIndexRoute
  '/_dashboard/wallet/': typeof DashboardWalletIndexRoute
  '/_dashboard/competitions/fixtures/$fixId': typeof DashboardCompetitionsFixturesFixIdRouteRouteWithChildren
  '/_dashboard/articles/$articleId/edit': typeof DashboardArticlesArticleIdEditRoute
  '/_dashboard/competitions/fixtures/review': typeof DashboardCompetitionsFixturesReviewRoute
  '/_dashboard/competitions/players/create': typeof DashboardCompetitionsPlayersCreateRoute
  '/_dashboard/competitions/stats/teams': typeof DashboardCompetitionsStatsTeamsRoute
  '/_dashboard/articles/create/': typeof DashboardArticlesCreateIndexRoute
  '/_dashboard/competitions/fixtures/': typeof DashboardCompetitionsFixturesIndexRoute
  '/_dashboard/competitions/leagues/': typeof DashboardCompetitionsLeaguesIndexRoute
  '/_dashboard/competitions/players/': typeof DashboardCompetitionsPlayersIndexRoute
  '/_dashboard/competitions/stats/': typeof DashboardCompetitionsStatsIndexRoute
  '/_dashboard/competitions/teams/': typeof DashboardCompetitionsTeamsIndexRoute
  '/_dashboard/competitions/fixtures/$fixId/player-stats': typeof DashboardCompetitionsFixturesFixIdPlayerStatsRoute
  '/_dashboard/competitions/fixtures/$fixId/raw-events': typeof DashboardCompetitionsFixturesFixIdRawEventsRoute
  '/_dashboard/competitions/fixtures/$fixId/review': typeof DashboardCompetitionsFixturesFixIdReviewRoute
  '/_dashboard/competitions/players/$playerId/edit': typeof DashboardCompetitionsPlayersPlayerIdEditRoute
  '/_dashboard/competitions/fixtures/$fixId/': typeof DashboardCompetitionsFixturesFixIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify'
    | '/api/uploadthing'
    | '/home/'
    | '/competitions/stats'
    | '/agents/fixtures'
    | '/admin/'
    | '/agents/'
    | '/articles/'
    | '/competitions/'
    | '/players/'
    | '/teams/'
    | '/tickets/'
    | '/wallet/'
    | '/competitions/fixtures/$fixId'
    | '/articles/$articleId/edit'
    | '/competitions/fixtures/review'
    | '/competitions/players/create'
    | '/competitions/stats/teams'
    | '/articles/create/'
    | '/competitions/fixtures/'
    | '/competitions/leagues/'
    | '/competitions/players/'
    | '/competitions/stats/'
    | '/competitions/teams/'
    | '/competitions/fixtures/$fixId/player-stats'
    | '/competitions/fixtures/$fixId/raw-events'
    | '/competitions/fixtures/$fixId/review'
    | '/competitions/players/$playerId/edit'
    | '/competitions/fixtures/$fixId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify'
    | '/api/uploadthing'
    | '/home'
    | '/agents/fixtures'
    | '/admin'
    | '/agents'
    | '/articles'
    | '/competitions'
    | '/players'
    | '/teams'
    | '/tickets'
    | '/wallet'
    | '/articles/$articleId/edit'
    | '/competitions/fixtures/review'
    | '/competitions/players/create'
    | '/competitions/stats/teams'
    | '/articles/create'
    | '/competitions/fixtures'
    | '/competitions/leagues'
    | '/competitions/players'
    | '/competitions/stats'
    | '/competitions/teams'
    | '/competitions/fixtures/$fixId/player-stats'
    | '/competitions/fixtures/$fixId/raw-events'
    | '/competitions/fixtures/$fixId/review'
    | '/competitions/players/$playerId/edit'
    | '/competitions/fixtures/$fixId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_dashboard'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/reset-password'
    | '/_auth/verify'
    | '/api/uploadthing'
    | '/home/'
    | '/_dashboard/competitions/stats'
    | '/_dashboard/agents/fixtures'
    | '/_dashboard/admin/'
    | '/_dashboard/agents/'
    | '/_dashboard/articles/'
    | '/_dashboard/competitions/'
    | '/_dashboard/players/'
    | '/_dashboard/teams/'
    | '/_dashboard/tickets/'
    | '/_dashboard/wallet/'
    | '/_dashboard/competitions/fixtures/$fixId'
    | '/_dashboard/articles/$articleId/edit'
    | '/_dashboard/competitions/fixtures/review'
    | '/_dashboard/competitions/players/create'
    | '/_dashboard/competitions/stats/teams'
    | '/_dashboard/articles/create/'
    | '/_dashboard/competitions/fixtures/'
    | '/_dashboard/competitions/leagues/'
    | '/_dashboard/competitions/players/'
    | '/_dashboard/competitions/stats/'
    | '/_dashboard/competitions/teams/'
    | '/_dashboard/competitions/fixtures/$fixId/player-stats'
    | '/_dashboard/competitions/fixtures/$fixId/raw-events'
    | '/_dashboard/competitions/fixtures/$fixId/review'
    | '/_dashboard/competitions/players/$playerId/edit'
    | '/_dashboard/competitions/fixtures/$fixId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  ApiUploadthingRoute: typeof ApiUploadthingRoute
  HomeIndexRoute: typeof HomeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploadthing': {
      id: '/api/uploadthing'
      path: '/api/uploadthing'
      fullPath: '/api/uploadthing'
      preLoaderRoute: typeof ApiUploadthingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/verify': {
      id: '/_auth/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_dashboard/wallet/': {
      id: '/_dashboard/wallet/'
      path: '/wallet'
      fullPath: '/wallet/'
      preLoaderRoute: typeof DashboardWalletIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/tickets/': {
      id: '/_dashboard/tickets/'
      path: '/tickets'
      fullPath: '/tickets/'
      preLoaderRoute: typeof DashboardTicketsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/teams/': {
      id: '/_dashboard/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof DashboardTeamsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/players/': {
      id: '/_dashboard/players/'
      path: '/players'
      fullPath: '/players/'
      preLoaderRoute: typeof DashboardPlayersIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/competitions/': {
      id: '/_dashboard/competitions/'
      path: '/competitions'
      fullPath: '/competitions/'
      preLoaderRoute: typeof DashboardCompetitionsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/articles/': {
      id: '/_dashboard/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof DashboardArticlesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/agents/': {
      id: '/_dashboard/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof DashboardAgentsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/admin/': {
      id: '/_dashboard/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/agents/fixtures': {
      id: '/_dashboard/agents/fixtures'
      path: '/agents/fixtures'
      fullPath: '/agents/fixtures'
      preLoaderRoute: typeof DashboardAgentsFixturesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/competitions/stats': {
      id: '/_dashboard/competitions/stats'
      path: '/competitions/stats'
      fullPath: '/competitions/stats'
      preLoaderRoute: typeof DashboardCompetitionsStatsRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/competitions/teams/': {
      id: '/_dashboard/competitions/teams/'
      path: '/competitions/teams'
      fullPath: '/competitions/teams/'
      preLoaderRoute: typeof DashboardCompetitionsTeamsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/competitions/stats/': {
      id: '/_dashboard/competitions/stats/'
      path: '/'
      fullPath: '/competitions/stats/'
      preLoaderRoute: typeof DashboardCompetitionsStatsIndexRouteImport
      parentRoute: typeof DashboardCompetitionsStatsRouteRoute
    }
    '/_dashboard/competitions/players/': {
      id: '/_dashboard/competitions/players/'
      path: '/competitions/players'
      fullPath: '/competitions/players/'
      preLoaderRoute: typeof DashboardCompetitionsPlayersIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/competitions/leagues/': {
      id: '/_dashboard/competitions/leagues/'
      path: '/competitions/leagues'
      fullPath: '/competitions/leagues/'
      preLoaderRoute: typeof DashboardCompetitionsLeaguesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/competitions/fixtures/': {
      id: '/_dashboard/competitions/fixtures/'
      path: '/competitions/fixtures'
      fullPath: '/competitions/fixtures/'
      preLoaderRoute: typeof DashboardCompetitionsFixturesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/articles/create/': {
      id: '/_dashboard/articles/create/'
      path: '/articles/create'
      fullPath: '/articles/create/'
      preLoaderRoute: typeof DashboardArticlesCreateIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/competitions/stats/teams': {
      id: '/_dashboard/competitions/stats/teams'
      path: '/teams'
      fullPath: '/competitions/stats/teams'
      preLoaderRoute: typeof DashboardCompetitionsStatsTeamsRouteImport
      parentRoute: typeof DashboardCompetitionsStatsRouteRoute
    }
    '/_dashboard/competitions/players/create': {
      id: '/_dashboard/competitions/players/create'
      path: '/competitions/players/create'
      fullPath: '/competitions/players/create'
      preLoaderRoute: typeof DashboardCompetitionsPlayersCreateRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/competitions/fixtures/review': {
      id: '/_dashboard/competitions/fixtures/review'
      path: '/competitions/fixtures/review'
      fullPath: '/competitions/fixtures/review'
      preLoaderRoute: typeof DashboardCompetitionsFixturesReviewRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/articles/$articleId/edit': {
      id: '/_dashboard/articles/$articleId/edit'
      path: '/articles/$articleId/edit'
      fullPath: '/articles/$articleId/edit'
      preLoaderRoute: typeof DashboardArticlesArticleIdEditRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/competitions/fixtures/$fixId': {
      id: '/_dashboard/competitions/fixtures/$fixId'
      path: '/competitions/fixtures/$fixId'
      fullPath: '/competitions/fixtures/$fixId'
      preLoaderRoute: typeof DashboardCompetitionsFixturesFixIdRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/competitions/fixtures/$fixId/': {
      id: '/_dashboard/competitions/fixtures/$fixId/'
      path: '/'
      fullPath: '/competitions/fixtures/$fixId/'
      preLoaderRoute: typeof DashboardCompetitionsFixturesFixIdIndexRouteImport
      parentRoute: typeof DashboardCompetitionsFixturesFixIdRouteRoute
    }
    '/_dashboard/competitions/players/$playerId/edit': {
      id: '/_dashboard/competitions/players/$playerId/edit'
      path: '/competitions/players/$playerId/edit'
      fullPath: '/competitions/players/$playerId/edit'
      preLoaderRoute: typeof DashboardCompetitionsPlayersPlayerIdEditRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/competitions/fixtures/$fixId/review': {
      id: '/_dashboard/competitions/fixtures/$fixId/review'
      path: '/review'
      fullPath: '/competitions/fixtures/$fixId/review'
      preLoaderRoute: typeof DashboardCompetitionsFixturesFixIdReviewRouteImport
      parentRoute: typeof DashboardCompetitionsFixturesFixIdRouteRoute
    }
    '/_dashboard/competitions/fixtures/$fixId/raw-events': {
      id: '/_dashboard/competitions/fixtures/$fixId/raw-events'
      path: '/raw-events'
      fullPath: '/competitions/fixtures/$fixId/raw-events'
      preLoaderRoute: typeof DashboardCompetitionsFixturesFixIdRawEventsRouteImport
      parentRoute: typeof DashboardCompetitionsFixturesFixIdRouteRoute
    }
    '/_dashboard/competitions/fixtures/$fixId/player-stats': {
      id: '/_dashboard/competitions/fixtures/$fixId/player-stats'
      path: '/player-stats'
      fullPath: '/competitions/fixtures/$fixId/player-stats'
      preLoaderRoute: typeof DashboardCompetitionsFixturesFixIdPlayerStatsRouteImport
      parentRoute: typeof DashboardCompetitionsFixturesFixIdRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthVerifyRoute: AuthVerifyRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface DashboardCompetitionsStatsRouteRouteChildren {
  DashboardCompetitionsStatsTeamsRoute: typeof DashboardCompetitionsStatsTeamsRoute
  DashboardCompetitionsStatsIndexRoute: typeof DashboardCompetitionsStatsIndexRoute
}

const DashboardCompetitionsStatsRouteRouteChildren: DashboardCompetitionsStatsRouteRouteChildren =
  {
    DashboardCompetitionsStatsTeamsRoute: DashboardCompetitionsStatsTeamsRoute,
    DashboardCompetitionsStatsIndexRoute: DashboardCompetitionsStatsIndexRoute,
  }

const DashboardCompetitionsStatsRouteRouteWithChildren =
  DashboardCompetitionsStatsRouteRoute._addFileChildren(
    DashboardCompetitionsStatsRouteRouteChildren,
  )

interface DashboardCompetitionsFixturesFixIdRouteRouteChildren {
  DashboardCompetitionsFixturesFixIdPlayerStatsRoute: typeof DashboardCompetitionsFixturesFixIdPlayerStatsRoute
  DashboardCompetitionsFixturesFixIdRawEventsRoute: typeof DashboardCompetitionsFixturesFixIdRawEventsRoute
  DashboardCompetitionsFixturesFixIdReviewRoute: typeof DashboardCompetitionsFixturesFixIdReviewRoute
  DashboardCompetitionsFixturesFixIdIndexRoute: typeof DashboardCompetitionsFixturesFixIdIndexRoute
}

const DashboardCompetitionsFixturesFixIdRouteRouteChildren: DashboardCompetitionsFixturesFixIdRouteRouteChildren =
  {
    DashboardCompetitionsFixturesFixIdPlayerStatsRoute:
      DashboardCompetitionsFixturesFixIdPlayerStatsRoute,
    DashboardCompetitionsFixturesFixIdRawEventsRoute:
      DashboardCompetitionsFixturesFixIdRawEventsRoute,
    DashboardCompetitionsFixturesFixIdReviewRoute:
      DashboardCompetitionsFixturesFixIdReviewRoute,
    DashboardCompetitionsFixturesFixIdIndexRoute:
      DashboardCompetitionsFixturesFixIdIndexRoute,
  }

const DashboardCompetitionsFixturesFixIdRouteRouteWithChildren =
  DashboardCompetitionsFixturesFixIdRouteRoute._addFileChildren(
    DashboardCompetitionsFixturesFixIdRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardCompetitionsStatsRouteRoute: typeof DashboardCompetitionsStatsRouteRouteWithChildren
  DashboardAgentsFixturesRoute: typeof DashboardAgentsFixturesRoute
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
  DashboardAgentsIndexRoute: typeof DashboardAgentsIndexRoute
  DashboardArticlesIndexRoute: typeof DashboardArticlesIndexRoute
  DashboardCompetitionsIndexRoute: typeof DashboardCompetitionsIndexRoute
  DashboardPlayersIndexRoute: typeof DashboardPlayersIndexRoute
  DashboardTeamsIndexRoute: typeof DashboardTeamsIndexRoute
  DashboardTicketsIndexRoute: typeof DashboardTicketsIndexRoute
  DashboardWalletIndexRoute: typeof DashboardWalletIndexRoute
  DashboardCompetitionsFixturesFixIdRouteRoute: typeof DashboardCompetitionsFixturesFixIdRouteRouteWithChildren
  DashboardArticlesArticleIdEditRoute: typeof DashboardArticlesArticleIdEditRoute
  DashboardCompetitionsFixturesReviewRoute: typeof DashboardCompetitionsFixturesReviewRoute
  DashboardCompetitionsPlayersCreateRoute: typeof DashboardCompetitionsPlayersCreateRoute
  DashboardArticlesCreateIndexRoute: typeof DashboardArticlesCreateIndexRoute
  DashboardCompetitionsFixturesIndexRoute: typeof DashboardCompetitionsFixturesIndexRoute
  DashboardCompetitionsLeaguesIndexRoute: typeof DashboardCompetitionsLeaguesIndexRoute
  DashboardCompetitionsPlayersIndexRoute: typeof DashboardCompetitionsPlayersIndexRoute
  DashboardCompetitionsTeamsIndexRoute: typeof DashboardCompetitionsTeamsIndexRoute
  DashboardCompetitionsPlayersPlayerIdEditRoute: typeof DashboardCompetitionsPlayersPlayerIdEditRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardCompetitionsStatsRouteRoute:
    DashboardCompetitionsStatsRouteRouteWithChildren,
  DashboardAgentsFixturesRoute: DashboardAgentsFixturesRoute,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
  DashboardAgentsIndexRoute: DashboardAgentsIndexRoute,
  DashboardArticlesIndexRoute: DashboardArticlesIndexRoute,
  DashboardCompetitionsIndexRoute: DashboardCompetitionsIndexRoute,
  DashboardPlayersIndexRoute: DashboardPlayersIndexRoute,
  DashboardTeamsIndexRoute: DashboardTeamsIndexRoute,
  DashboardTicketsIndexRoute: DashboardTicketsIndexRoute,
  DashboardWalletIndexRoute: DashboardWalletIndexRoute,
  DashboardCompetitionsFixturesFixIdRouteRoute:
    DashboardCompetitionsFixturesFixIdRouteRouteWithChildren,
  DashboardArticlesArticleIdEditRoute: DashboardArticlesArticleIdEditRoute,
  DashboardCompetitionsFixturesReviewRoute:
    DashboardCompetitionsFixturesReviewRoute,
  DashboardCompetitionsPlayersCreateRoute:
    DashboardCompetitionsPlayersCreateRoute,
  DashboardArticlesCreateIndexRoute: DashboardArticlesCreateIndexRoute,
  DashboardCompetitionsFixturesIndexRoute:
    DashboardCompetitionsFixturesIndexRoute,
  DashboardCompetitionsLeaguesIndexRoute:
    DashboardCompetitionsLeaguesIndexRoute,
  DashboardCompetitionsPlayersIndexRoute:
    DashboardCompetitionsPlayersIndexRoute,
  DashboardCompetitionsTeamsIndexRoute: DashboardCompetitionsTeamsIndexRoute,
  DashboardCompetitionsPlayersPlayerIdEditRoute:
    DashboardCompetitionsPlayersPlayerIdEditRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  ApiUploadthingRoute: ApiUploadthingRoute,
  HomeIndexRoute: HomeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
